// AUTO-GENERATED by scripts/write-build-info.mjs. Do not edit by hand.
// Regenerated each build to capture the git + version state at build time.
export interface BuildInfo {
  branch: string;
  commit: string;
  commitShort: string;
  dirty: boolean;
  builtAt: string;
  appVersion: string;
  androidVersionCode: number | null;
}
export const BUILD_INFO: BuildInfo = {
  "branch": "claude/add-steering-obstacles-WCPxr",
  "commit": "136ac98c9ea6e608e879c9211fe997131c4a2231",
  "commitShort": "136ac98",
  "dirty": true,
  "builtAt": "2026-05-07T21:53:54.191Z",
  "appVersion": "0.0.1",
  "androidVersionCode": 3
};
