// AUTO-GENERATED by scripts/write-build-info.mjs. Do not edit by hand.
// Regenerated each build to capture the git + version state at build time.
export interface BuildInfo {
  branch: string;
  commit: string;
  commitShort: string;
  dirty: boolean;
  builtAt: string;
  appVersion: string;
  androidVersionCode: number | null;
}
export const BUILD_INFO: BuildInfo = {
  "branch": "claude/add-steering-obstacles-WCPxr",
  "commit": "3da1d4c46f539b4dd7f9a0dab83f1133b41427dc",
  "commitShort": "3da1d4c",
  "dirty": true,
  "builtAt": "2026-05-07T02:22:00.154Z",
  "appVersion": "0.0.1",
  "androidVersionCode": 3
};
