// AUTO-GENERATED by scripts/write-build-info.mjs. Do not edit by hand.
// Regenerated each build to capture the git + version state at build time.
export interface BuildInfo {
  branch: string;
  commit: string;
  commitShort: string;
  dirty: boolean;
  builtAt: string;
  appVersion: string;
  androidVersionCode: number | null;
}
export const BUILD_INFO: BuildInfo = {
  "branch": "claude/add-steering-obstacles-WCPxr",
  "commit": "927b8ca85dc5255e5c414b7a5c514fa6dc92add8",
  "commitShort": "927b8ca",
  "dirty": true,
  "builtAt": "2026-05-06T04:01:23.681Z",
  "appVersion": "0.0.1",
  "androidVersionCode": 3
};
