// AUTO-GENERATED by scripts/embed-html.mjs. Do not edit by hand.
// Placeholder content checked in so TypeScript can resolve the import.
// CI overwrites this with the real Vite-built HTML before Metro bundles.
export const HTML_BUNDLE = '';
