// Reads dist/index.html (produced by `vite build`) and writes it into
// src/__generated__/html-bundle.ts as an exported string constant.
// This lets App.tsx import the entire game inline as JS, avoiding
// require('./dist/index.html') which Metro / expo-cli was choking on
// when exporting the OTA bundle.
//
// Run automatically as part of `npm run web:build` after the Vite build.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';

const INPUT  = 'dist/index.html';
const OUTPUT = 'src/__generated__/html-bundle.ts';

if (!existsSync(INPUT)) {
  console.error(`embed-html: ${INPUT} not found. Did 'vite build' run first?`);
  process.exit(1);
}

const html = readFileSync(INPUT, 'utf8');
const literal = JSON.stringify(html);

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT,
  `// AUTO-GENERATED by scripts/embed-html.mjs. Do not edit by hand.\n` +
  `// Regenerated each build from dist/index.html.\n` +
  `export const HTML_BUNDLE = ${literal};\n`
);

console.log(`embed-html: wrote ${OUTPUT} (${(html.length / 1024).toFixed(1)} KB)`);
